"use client";
import { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import { Trophy, Search, Download, FileText, CheckCircle, UserX, Loader2, ArrowLeft, Menu } from "lucide-react";
import toast from "react-hot-toast";
import StudentClassroomSidebar from "@/components/classroom/StudentClassroomSidebar"; // ✅ Real Sidebar

export default function LeaderboardPage() {
  const params = useParams();
  const router = useRouter();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [downloading, setDownloading] = useState(false);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  // Fetch Data
  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await fetch(`/api/courses/${params.id}/tests/${params.testId}/leaderboard`);
        const json = await res.json();
        if (json.success) {
            setData(json);
        } else {
            toast.error(json.error || "Failed to load data");
        }
      } catch (error) {
        toast.error("Network Error");
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, [params.id, params.testId]);

  // --- 🖨️ PDF GENERATION LOGIC ---
  const generatePDF = async (type) => {
    if (!data?.test?.questions) return toast.error("Questions not available");
    
    setDownloading(true);
    const isSolution = type === 'solution';

    if (typeof window !== "undefined" && !window.html2pdf) {
        await new Promise((resolve) => {
            const script = document.createElement('script');
            script.src = "https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js";
            script.onload = resolve;
            document.body.appendChild(script);
        });
    }

    const element = document.createElement('div');
    element.innerHTML = `
      <div style="font-family: Arial, sans-serif; color: #000; padding: 20px; font-size: 10px; line-height: 1.4;">
        <div style="background-color: #FFD700; color: #000; padding: 15px; border-radius: 6px; margin-bottom: 20px; text-align: center; border: 2px solid #000;">
            <h1 style="margin: 0; font-size: 18px; text-transform: uppercase; font-weight: 900;">${data.test.title}</h1>
            <p style="margin: 5px 0 0; font-size: 11px; font-weight: bold;">${isSolution ? 'DETAILED SOLUTIONS KEY' : 'QUESTION PAPER'}</p>
        </div>
        <div style="display: flex; flex-direction: column; gap: 15px;">
            ${data.test.questions.map((q, idx) => `
                <div style="border-bottom: 1px dashed #ccc; padding-bottom: 10px; page-break-inside: avoid;">
                    <div style="font-weight: bold; font-size: 11px; margin-bottom: 6px;">
                        <span style="background: #000; color: #FFD700; padding: 2px 5px; border-radius: 3px; margin-right: 5px;">Q${idx + 1}</span>
                        ${q.questionText}
                    </div>
                    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 5px; margin-left: 5px;">
                        ${q.options.map((opt, oIdx) => `
                            <div style="
                                padding: 3px 6px; border-radius: 3px; font-size: 10px;
                                ${isSolution && oIdx === q.correctOption ? 'background: #e6fffa; border: 1px solid #006400; color: #006400; font-weight: bold;' : 'background: #f9f9f9; border: 1px solid #eee;'}
                            ">
                                ${String.fromCharCode(65 + oIdx)}. ${opt}
                                ${isSolution && oIdx === q.correctOption ? '✅' : ''}
                            </div>
                        `).join('')}
                    </div>
                    ${isSolution && q.description ? `
                        <div style="margin-top: 8px; background: #fffbe6; padding: 8px; border-left: 3px solid #FFD700; font-size: 9px; color: #444;">
                            <strong>💡 Explanation:</strong> ${q.description}
                        </div>
                    ` : ''}
                </div>
            `).join('')}
        </div>
        <div style="margin-top: 30px; text-align: center; font-size: 8px; color: #666; border-top: 1px solid #eee; padding-top: 10px;">
            Generated by LearnR Portal • Professional Exam Suite
        </div>
      </div>
    `;

    const opt = {
      margin:       10,
      filename:     `${data.test.title.replace(/\s+/g, '_')}_${isSolution ? 'Solution' : 'Paper'}.pdf`,
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { scale: 2, useCORS: true },
      jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    try {
        await window.html2pdf().set(opt).from(element).save();
        toast.success("PDF Downloaded Successfully!");
    } catch (err) {
        console.error(err);
        toast.error("Download Failed");
    } finally {
        setDownloading(false);
    }
  };

  const filteredLeaderboard = data?.leaderboard?.filter(u => 
    u.name.toLowerCase().includes(searchQuery.toLowerCase())
  ) || [];

  if (loading) return (
    <div className="fixed inset-0 bg-black z-[200] flex items-center justify-center">
        <Loader2 className="animate-spin text-yellow-500" size={40}/>
    </div>
  );

  // --- ✅ FIX: Smart Tab Handler ---
  // This ensures that when you click a sidebar tab, it takes you to the EXACT tab, not just Overview.
  const handleSidebarTabChange = (newTab) => {
      // Navigate to classroom page with ?tab=... query param
      router.push(`/dashboard/classroom/${params.id}?tab=${newTab}`);
  };

  return (
    <div className="fixed inset-0 bg-[#050505] z-[100] overflow-hidden flex flex-col md:flex-row text-white font-sans selection:bg-yellow-500 selection:text-black">
      
      {/* 1. Using REAL Classroom Sidebar with Correct Logic */}
      <StudentClassroomSidebar 
          activeTab="tests" // Highlight 'Tests' because we are inside a test result
          setActiveTab={handleSidebarTabChange} // Pass our smart handler function
          courseTitle={data?.test?.title || "Exam Result"} 
      />

      {/* 2. Main Content Area */}
      <div className="flex-1 relative h-full overflow-y-auto scroll-smooth md:ml-64 pt-14 pb-20 md:py-0 md:pb-0">
        
        {/* Mobile Header */}
        <div className="md:hidden fixed top-0 left-0 right-0 h-14 bg-black/90 backdrop-blur-md border-b border-white/10 flex items-center px-4 z-50 justify-between">
             <div className="flex items-center gap-3">
                 <button onClick={() => router.back()} className="p-1 text-gray-400 hover:text-white">
                    <ArrowLeft size={20}/>
                 </button>
                 <span className="font-bold text-sm line-clamp-1">{data?.test?.title}</span>
             </div>
        </div>

        {/* Scrollable Content */}
        <div className="p-4 md:p-8 space-y-8 max-w-5xl mx-auto">
            
            {/* Download Card */}
            <div className="bg-[#0a0a0a] border border-white/10 rounded-2xl p-6 relative overflow-hidden group">
                <div className="absolute top-0 right-0 p-8 opacity-5 group-hover:opacity-10 transition-opacity">
                    <Download size={120} className="text-yellow-500"/>
                </div>
                
                <h2 className="text-xl font-black text-yellow-500 mb-2 flex items-center gap-2">
                    <FileText size={24}/> DOWNLOAD RESOURCES
                </h2>
                <p className="text-gray-400 text-xs md:text-sm mb-6 max-w-lg leading-relaxed">
                    Access exam materials directly. Download the optimized PDF for offline practice or analysis.
                </p>

                <div className="flex flex-col sm:flex-row gap-4">
                    <button 
                        onClick={() => generatePDF('question')}
                        disabled={downloading}
                        className="flex-1 py-3 px-4 bg-white/5 border border-white/10 rounded-xl font-bold hover:bg-white/10 hover:border-yellow-500/30 transition-all flex items-center justify-center gap-2 text-xs md:text-sm disabled:opacity-50"
                    >
                       {downloading ? <Loader2 className="animate-spin" size={16}/> : <FileText size={18} className="text-gray-400"/>} 
                       Download Question Paper
                    </button>
                    <button 
                        onClick={() => generatePDF('solution')}
                        disabled={downloading}
                        className="flex-1 py-3 px-4 bg-yellow-500 text-black rounded-xl font-bold hover:bg-yellow-400 transition-all flex items-center justify-center gap-2 text-xs md:text-sm shadow-[0_0_20px_rgba(234,179,8,0.2)] disabled:opacity-50"
                    >
                        {downloading ? <Loader2 className="animate-spin" size={16}/> : <CheckCircle size={18}/>}
                        Download with Solutions
                    </button>
                </div>
            </div>

            {/* Leaderboard Table */}
            <div className="space-y-4">
                <div className="flex flex-col md:flex-row justify-between items-end gap-4">
                    <h2 className="text-xl md:text-2xl font-black text-white flex items-center gap-3">
                        <Trophy className="text-yellow-500" /> TOP PERFORMERS
                    </h2>
                    
                    <div className="relative w-full md:w-64">
                        <Search className="absolute left-3 top-2.5 text-gray-500" size={16}/>
                        <input 
                            type="text" 
                            placeholder="Search by name..." 
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            className="w-full bg-[#111] border border-white/10 rounded-full py-2 pl-10 pr-4 text-xs text-white focus:border-yellow-500 outline-none transition-all"
                        />
                    </div>
                </div>

                <div className="bg-[#0a0a0a] border border-white/10 rounded-2xl overflow-hidden shadow-2xl">
                    <div className="overflow-x-auto">
                        <table className="w-full text-left border-collapse">
                            <thead>
                                <tr className="bg-white/5 text-gray-500 text-[10px] md:text-xs font-mono uppercase tracking-widest">
                                    <th className="p-4">Rank</th>
                                    <th className="p-4">Cadet Name</th>
                                    <th className="p-4 text-center">Score</th>
                                    <th className="p-4 text-right">Status</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-white/5 text-xs md:text-sm">
                                {filteredLeaderboard.map((user, idx) => (
                                    <tr 
                                        key={idx} 
                                        className={`
                                            transition-colors hover:bg-white/[0.02]
                                            ${user.isCurrentUser ? 'bg-yellow-500/10 border-l-2 border-yellow-500' : ''}
                                        `}
                                    >
                                        <td className="p-4 font-mono font-bold text-gray-400">
                                            {user.rank === 1 ? <span className="text-yellow-400 text-base">#1 👑</span> :
                                             user.rank === 2 ? <span className="text-gray-300 text-base">#2 🥈</span> :
                                             user.rank === 3 ? <span className="text-orange-400 text-base">#3 🥉</span> :
                                             user.rank === "-" ? "-" : `#${user.rank}`}
                                        </td>
                                        <td className="p-4">
                                            <div className="font-bold text-white flex items-center gap-2">
                                                {user.name}
                                                {user.isCurrentUser && <span className="text-[9px] bg-yellow-500 text-black px-1.5 py-0.5 rounded font-black tracking-wide">YOU</span>}
                                            </div>
                                        </td>
                                        <td className="p-4 text-center font-mono text-yellow-500 font-bold text-sm">
                                            {user.status === "Absent" ? <span className="text-gray-700">-</span> : user.score}
                                        </td>
                                        <td className="p-4 text-right">
                                            {user.status === "Present" ? (
                                                <span className="inline-flex items-center gap-1 text-[10px] text-green-400 bg-green-900/20 px-2 py-1 rounded border border-green-500/20">
                                                    <CheckCircle size={10}/> Present
                                                </span>
                                            ) : (
                                                <span className="inline-flex items-center gap-1 text-[10px] text-red-400 bg-red-900/20 px-2 py-1 rounded border border-red-500/20">
                                                    <UserX size={10}/> Absent
                                                </span>
                                            )}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                        
                        {filteredLeaderboard.length === 0 && (
                            <div className="p-10 text-center text-gray-600 text-xs font-mono uppercase tracking-widest">
                                No records found
                            </div>
                        )}
                    </div>
                </div>
            </div>

        </div>
      </div>
    </div>
  );
}